// contexts/LanguageContext.tsx
'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'si';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'preferred_language';
const EXPIRY_KEY = 'language_expiry';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    const storedLanguage = sessionStorage.getItem(STORAGE_KEY);
    const expiryTime = sessionStorage.getItem(EXPIRY_KEY);

    if (storedLanguage && expiryTime) {
      const now = new Date().getTime();
      const expiry = parseInt(expiryTime, 10);

      if (now < expiry) {
        setLanguageState(storedLanguage as Language);
      } else {
        sessionStorage.removeItem(STORAGE_KEY);
        sessionStorage.removeItem(EXPIRY_KEY);
      }
    }
    setIsInitialized(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    const expiryTime = new Date().getTime() + (24 * 60 * 60 * 1000);
    sessionStorage.setItem(STORAGE_KEY, lang);
    sessionStorage.setItem(EXPIRY_KEY, expiryTime.toString());
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function hasStoredLanguage(): boolean {
  if (typeof window === 'undefined') return false;

  const storedLanguage = sessionStorage.getItem(STORAGE_KEY);
  const expiryTime = sessionStorage.getItem(EXPIRY_KEY);

  if (!storedLanguage || !expiryTime) return false;

  const now = new Date().getTime();
  const expiry = parseInt(expiryTime, 10);

  return now < expiry;
}

const translations = {
  en: {
    header: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      routes: 'Routes',
      contact: 'Contact',
      bookNow: 'Book Now',
    },
    footer: {
      quickLinks: 'Quick Links',
      followUs: 'Follow Us',
      allRightsReserved: 'All rights reserved',
      privacyPolicy: 'Privacy Policy',
      terms: 'Terms & Conditions',
    },
    booking: {
      title: 'Book Your Ticket',
      selectRoute: 'Select Your Route',
      chooseJourney: 'Choose your journey from available routes',
      selectBus: 'Select Bus, Date & Details',
      selectSeats: 'Select Your Seats',
      passengerDetails: 'Passenger Details',
      travelDate: 'Travel Date',
      passengers: 'Number of Passengers',
      passenger: 'Passenger',
      passengers_plural: 'Passengers',
      pickupLocation: 'Pickup Location',
      selectPickup: 'Select pickup location',
      availableBuses: 'Available Buses',
      noBuses: 'No buses available on this route',
      seats: 'seats',
      seat: 'Seat',
      back: 'Back',
      departureSoon: 'Departure Soon',
      continue: 'Continue',
      bookingConfirmed: 'Booking Confirmed!',
      bookingSuccess: 'Your booking has been successfully created. Please save your booking ID for future reference.',
      bookingId: 'Booking ID',
      backToHome: 'Back to Home',
      fullName: 'Name',
      enterFullName: 'Enter your name',
      phoneNumber: 'Phone Number',
      enterPhone: '+94 71 234 5678',
      email: 'Email',
      findYourRoute: 'Select your route from here.',
      selectLocations: 'Choose Departure and arrival locations from below',
      bookingHelp: 'Need Help with Bookings?',
      enterEmail: 'your@email.com',
      optional: 'Optional',
      confirmBooking: 'Confirm Booking',
      processing: 'Processing...',
      route: 'Route',
      bus: 'Bus',
      date: 'Date',
      totalAmount: 'Total Amount',
      pricePerSeat: 'Price per seat',
      selectedSeats: 'Selected Seats',
      selectedBus: 'Selected Bus',
      available: 'Available',
      selected: 'Selected',
      booked: 'Booked',
      driver: 'Driver',
      selectionSummary: 'Selection Summary',
      bookingSummary: 'Booking Summary',
      bookingDetails: 'Booking Details',
      important: 'Important',
      arriveEarly: 'Please arrive 15 minutes before departure',
      carryId: 'Carry a SMS and mobile number for verification',
      saveBookingId: 'Save your booking ID for reference',
      continueToSeats: 'Continue to Seat Selection',
      continueToDetails: 'Continue to Details',
      selectMoreSeats: 'Select',
      moreSeats: 'Choose more seat(s)',
      pickupPoints: 'Pickup Points',
      minutes: 'minutes',
      startingPoint: 'Starting Point',
      fillAllFields: 'Please fill all required fields',
      selectRouteFirst: 'Please select a route first',
      completeBusDetails: 'Please complete bus and travel details first',
      selectSeatsFirst: 'Please select your seats first',
      onlySelect: 'You can only select',
      failedFetchRoutes: 'Failed to fetch routes',
      failedFetchBuses: 'Failed to fetch buses',
      failedFetchSeats: 'Failed to fetch available seats',
      bookingCreated: 'Booking created successfully!',
      failedCreateBooking: 'Failed to create booking',
      goToStep: 'Go to step',
      completePrevious: 'Complete previous steps first',
      seatLayout: 'Seat Layout',
      bookYourBusTicket: 'Book Your Bus Ticket',
      from: 'From',
      to: 'To',
      searchBuses: 'Search Buses',
      popularRoutes: 'Popular Routes',
      departsIn: 'Departs in',
      min: 'min',
      notSet: 'Not set',
      routeComingSoon: 'This route is coming soon and not available for booking yet',
      routeComingSoonDesc: 'Please check back later or choose another route',
      routeSelected: 'Route selected',
      locked: 'Locked',
      noneSelected: 'None selected',
      subtotal: 'Subtotal',
      lkr: 'LKR',
      perSeat: 'per seat',
      serviceFee: 'Service Fee',
      more: 'more',
      comingSoon: 'Coming Soon',
      notAvailableYet: 'Not available for booking yet',
      howToBook: 'How to Book Your Ticket',
      followSteps: 'Follow these simple steps to complete your booking',
      step: 'STEP',
      searchRoute: 'Search Route',
      searchRouteDesc: 'Select your departure and destination locations to find available routes',
      selectSeatsTitle: 'Select Seats',
      selectSeatsDesc: 'Choose your preferred bus, travel date, and select your seats from the layout',
      confirmBookingTitle: 'Confirm Booking',
      confirmBookingDesc: 'Enter your details and confirm your booking to receive your ticket',
      note: 'Note',
      serviceFeeNote: 'A service fee of',
      findRouteInstantly: 'Find Your Route Instantly',
      selectJourneyDetails: 'Select your journey details below to view available trips',
      departureLocation: 'Departure Location',
      whereLeaving: 'Where are you leaving from?',
      allLocations: 'All Locations',
      arrivalLocation: 'Arrival Location',
      whereGoing: 'Where are you going?',
      allDestinations: 'All Destinations',
      clearFilters: 'Clear Filters',
      routeFound: 'route found',
      routesFound: 'routes found',
      noRoutesFound: 'No Routes Found',
      noRoutesFoundDesc: 'No routes available for the selected locations',
      selectBusDesc: 'Choose your bus and travel date',
      selectedRoute: 'Selected Route',
      tripDetails: 'Trip Details',
      choosePreferredSeats: 'Choose your preferred seats',
      enterContactInfo: 'Enter your contact information to complete booking',
      contactInformation: 'Contact Information',
    },
    common: {
      welcome: 'Welcome',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      backToHome: 'Back to Home',
      cancel: 'Cancel',
      confirm: 'Confirm',
      close: 'Close',
    },
    hero: {
      title: {
        line1: 'Your Journey',
        line2: 'Starts Here'
      },
      description: 'Experience comfortable, safe, and reliable bus travel across beautiful Sri Lanka.',
      bookButton: 'Book Your Seat',
      imageAlt: {
        mountains: 'Sri Lankan bus journey through mountains',
        interior: 'Comfortable bus interior',
        landscape: 'Beautiful Sri Lankan landscape',
        mountainsMobile: 'Sri Lankan bus journey - mobile view',
        interiorMobile: 'Comfortable bus interior - mobile view',
        landscapeMobile: 'Beautiful landscape - mobile view'
      }
    },
    about: {
      title: 'Your Trusted Travel Partner',
      since: 'Since 1995',
      subtitle: 'Connecting hearts, destinations, and dreams across the beautiful island of Sri Lanka with safe, comfortable, and reliable transportation services.',
      ourStory: 'About Us',
      storyParagraph1: 'Welcome to Bus Seat Booking, your trusted partner for easy and reliable bus ticket booking. We are dedicated to simplifying your travel by providing a seamless, one-stop platform to find, compare, and book bus seats to your favorite destinations. Our mission is to make bus travel more accessible and convenient for everyone. We connect you with a vast network of bus operators, offering a wide selection of routes, schedules, and bus types to fit every budget and comfort level.',
      storyParagraph2: "Whether you're planning a daily commute, a weekend getaway, or a long-distance journey, our user-friendly website ensures you can book your tickets in just a few clicks—anytime, anywhere. We believe in safe journeys, transparent pricing, and dedicated customer support. Thank you for choosing us to help you reach your destination.",
      islandWideCoverage: 'Island-Wide Coverage',
      coverageDescription: 'Connecting all major cities and towns',
      onTimeRate: 'On-Time Rate',
      customerRating: 'Customer Rating',
      trustedBy: 'Trusted by Thousands Across Sri Lanka',
      numbersSpeak: 'Numbers that speak for our commitment to excellence',
      happyPassengers: 'Happy Passengers',
      routesCovered: 'Routes Covered',
      modernBuses: 'Modern Buses',
      yearsExperience: 'Years Experience',
      bookNextTrip: 'Book your next trip with confidence',
      swipeToStart: 'Swipe to start your journey',
      redirecting: 'Redirecting...',
      experience25Years: '25+ Years Experience',
      experience25YearsDesc: 'Serving Sri Lanka with excellence since 1995, building trust through reliable service',
      happyCustomers1M: '1M+ Happy Customers',
      happyCustomers1MDesc: 'Trusted by millions of passengers nationwide with 98% satisfaction rate',
      safetyRecord100: '100% Safety Record',
      safetyRecord100Desc: 'Maintaining highest safety standards with zero accidents in the last 5 years',
      service247: '24/7 Service',
      service247Desc: 'Round-the-clock customer support and emergency assistance available',
    },
    services: {
      title: 'Our Premium Services',
      subtitle: 'Experience world-class amenities and services designed to make your journey across Sri Lanka comfortable and memorable.',
      luxuryBuses: 'Luxury Buses',
      luxuryBusesDesc: 'Modern, comfortable buses with reclining seats and ample legroom for the ultimate travel experience',
      safeTravel: 'Safe Travel',
      safeTravelDesc: 'Experienced drivers and regular vehicle maintenance for your safety with 24/7 monitoring systems',
      airConditioning: 'Air Conditioning',
      airConditioningDesc: 'Climate-controlled environment for comfortable travel in all weather conditions',
      learnMore: 'Learn More',
      readyToExperience: 'Ready to Experience Premium Travel?',
      readyToExperienceDesc: 'Book your journey today and enjoy our world-class services that make every trip a comfortable and safe experience.',
      bookYourTrip: 'Book Your Trip',
      viewAllRoutes: 'View All Routes',
    },
    routes: {
      title: 'Popular',
      titleHighlight: 'Routes',
      subtitle: 'Choose from our most traveled routes and experience premium comfort',
      loadingRoutes: 'Loading routes...',
      noRoutesAvailable: 'No Routes Available',
      checkBackLater: 'Check back later for available routes.',
      duration: 'Duration',
      distance: 'Distance',
      pickupPoints: 'Pickup Points',
      more: 'more',
      bookThisRoute: 'Book This Route',
      exploreAllRoutes: 'Explore All Routes',
      startingFrom: 'Starting from',
    },
    contact: {
      title: 'Get in Touch',
      subtitle: 'Have questions or need assistance? Our friendly team is ready to help you plan your perfect journey.',
      contactInformation: 'Contact Information',
      headOffice: 'Head Office',
      headOfficeAddress: '123 Main Street, Colombo 07\nSri Lanka',
      phoneNumbers: 'Phone Numbers',
      hotline: 'Hotline',
      mobile: 'Mobile',
      email: 'Email',
      officeHours: 'Office Hours',
      officeHoursWeekday: 'Monday - Saturday: 6:00 AM - 10:00 PM',
      officeHoursSunday: 'Sunday: 7:00 AM - 9:00 PM',
      mapComingSoon: 'Interactive Map Coming Soon',
      sendMessage: 'Send us a Message',
      firstName: 'First Name',
      firstNamePlaceholder: 'Your first name',
      lastName: 'Last Name',
      lastNamePlaceholder: 'Your last name',
      emailAddress: 'Email Address',
      emailPlaceholder: 'your.email@example.com',
      phoneNumber: 'Phone Number',
      phonePlaceholder: '+94 XX XXX XXXX',
      subject: 'Subject',
      selectSubject: 'Select a subject',
      bookingInquiry: 'Booking Inquiry',
      complaint: 'Complaint',
      suggestion: 'Suggestion',
      other: 'Other',
      message: 'Message',
      messagePlaceholder: 'Tell us how we can help you...',
      sendMessageButton: 'Send Message',
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Find answers to common questions about our services, booking process, and travel policies.',
      stillHaveQuestions: 'Still have questions? We\'re here to help!',
      contactSupport: 'Contact Support',
      question1: 'How can I book a bus ticket with Wijitha Travels?',
      answer1: 'You can book tickets online through our website, mobile app, or visit any of our booking counters. Online booking is available 24/7 and offers instant confirmation.',
      question2: 'What is your cancellation and refund policy?',
      answer2: 'Cancellations made 24 hours before departure receive a full refund minus processing fee. Cancellations within 24 hours are subject to a 25% deduction. No refunds for no-shows.',
      question3: 'Are your buses air-conditioned?',
      answer3: 'Yes, all our buses are equipped with modern air conditioning systems. We also have luxury buses with individual climate controls for premium comfort.',
      question4: 'What safety measures do you have in place?',
      answer4: 'We maintain strict safety protocols including regular vehicle maintenance, GPS tracking, trained drivers, first aid kits, and 24/7 monitoring of all trips.',
      question5: 'Can I choose my seat when booking?',
      answer5: 'Yes, our online booking system allows you to select your preferred seat from available options. Premium seats are available at a small additional cost.',
      question6: 'Do you provide meals during long journeys?',
      answer6: 'On routes longer than 6 hours, we provide complimentary snacks and refreshments. Meal stops are scheduled for journeys over 8 hours.',
      question7: 'What if my bus is delayed or cancelled?',
      answer7: 'In case of delays, we notify passengers via SMS/email. For cancellations, we arrange alternative transport or provide full refunds. Compensation may apply for significant delays.',
      question8: 'Is there WiFi available on buses?',
      answer8: 'Yes, most of our buses offer complimentary WiFi. Entertainment systems with movies, music, and games are available on luxury routes.',
    },
    whyChooseUs: {
      title: 'Why Choose Wijitha Travels?',
      subtitle: "We're not just a bus service - we're your travel partner committed to making every journey safe, comfortable, and memorable.",
      safetyFirst: 'Safety First',
      safetyFirstDesc: 'Our top priority is your safety. All our buses undergo regular maintenance and our drivers are thoroughly trained and experienced.',
      onTimeGuarantee: 'On-Time Guarantee',
      onTimeGuaranteeDesc: 'We value your time. Our buses follow strict schedules and we guarantee punctual departures and arrivals.',
      bestPrices: 'Best Prices',
      bestPricesDesc: 'Enjoy competitive pricing without compromising on quality. We offer the best value for money in Sri Lanka.',
      support247: '24/7 Support',
      support247Desc: 'Our customer service team is available round the clock to assist you with bookings, queries, and support.',
      awardWinning: 'Award Winning',
      awardWinningDesc: "Recognized as Sri Lanka's best bus service provider for three consecutive years by the National Transport Board.",
      trustedByMillions: 'Trusted by Millions',
      trustedByMillionsDesc: 'Over 1 million satisfied customers have chosen us for their travel needs. Join our family of happy travelers.',
      readyToExperience: 'Ready to Experience the Difference?',
      readyToExperienceDesc: 'Join thousands of satisfied customers who trust Wijitha Travels for their journey',
      bookYourTrip: 'Book Your Trip',
      contactUs: 'Contact Us',
    },
    terms: {
      title: 'Terms & Conditions',
      mainTitle: 'Terms and Conditions',
      mainDescription: 'Please read these terms and conditions carefully before using our bus booking service. By booking a ticket, you agree to be bound by these terms.',
      lastUpdated: 'Last Updated',
      importantNotice: 'Important Notice',
      importantNoticeText: 'By using our booking service and making a reservation, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, please do not use our service.',

      section1: {
        title: '1. General Terms of Service',
        content: 'These terms govern your use of our online bus booking platform and services. All bookings made through our platform are subject to these terms and conditions.',
        point1: 'All users must be at least 18 years old to make a booking, or have parental/guardian consent.',
        point2: 'You agree to provide accurate, current, and complete information during the booking process.',
        point3: 'You are responsible for maintaining the confidentiality of your booking information.',
        point4: 'We reserve the right to refuse service or cancel bookings that violate these terms.',
      },

      section2: {
        title: '2. Booking and Payment Terms',
        content: 'All bookings must be completed online through our secure payment gateway. Payment is required at the time of booking to confirm your reservation.',
        point1: 'All prices are displayed in Sri Lankan Rupees (LKR) and include applicable taxes unless otherwise stated.',
        point2: 'A non-refundable service fee is charged per booking to cover operational costs.',
        point3: 'Payment must be completed within the session time, or the selected seats will be released.',
        point4: 'We accept major credit cards, debit cards, and digital payment methods through our secure payment partner.',
        point5: 'Once payment is confirmed, you will receive a booking confirmation with a unique booking ID.',
      },

      section3: {
        title: '3. Cancellation and Refund Policy',
        content: 'Cancellations are subject to our refund policy. Please read carefully before making a booking.',
        point1: 'Cancellations made 24 hours or more before departure time: 80% refund (service fee non-refundable).',
        point2: 'Cancellations made between 12-24 hours before departure: 50% refund (service fee non-refundable).',
        point3: 'Cancellations made less than 12 hours before departure: No refund.',
        point4: 'Refunds will be processed within 7-10 business days to the original payment method.',
      },

      section4: {
        title: '4. Passenger Responsibilities',
        content: 'As a passenger, you are required to comply with the following responsibilities and requirements.',
        point1: 'Arrive at the designated pickup location at least 15 minutes before the scheduled departure time.',
        point2: 'Carry a valid government-issued photo ID for verification purposes.',
        point3: 'Maintain appropriate behavior and respect other passengers and bus staff.',
        point4: 'No smoking, alcohol consumption, or illegal activities are permitted on the bus.',
      },

      section5: {
        title: '5. Liability Limitations',
        content: 'Our liability is limited as outlined below. Please read these limitations carefully.',
        point1: 'We are not liable for delays, cancellations, or route changes due to weather, traffic, mechanical issues, or other circumstances beyond our control.',
        point2: 'Passengers are responsible for their personal belongings. We are not liable for lost, stolen, or damaged items.',
        point3: 'Our maximum liability for any claim shall not exceed the ticket price paid by the passenger.',
      },

      section6: {
        title: '6. Privacy and Data Protection',
        content: 'We are committed to protecting your personal information and privacy.',
        point1: 'Personal information collected during booking is used solely for service delivery and communication.',
        point2: 'We do not sell or share your personal data with third parties except as required for payment processing.',
        point3: 'For more details, please refer to our Privacy Policy page.',
      },

      questions: 'Questions or Concerns?',
      questionsText: 'If you have any questions about these Terms and Conditions, please contact us:',
      email: 'Email',
      phone: 'Phone',
    },

    // PRIVACY POLICY TRANSLATIONS
    privacy: {
      title: 'Privacy Policy',
      mainTitle: 'Privacy Policy',
      mainDescription: 'We are committed to protecting your privacy and personal information. This policy explains how we collect, use, and safeguard your data when you use our bus booking service.',
      lastUpdated: 'Last Updated',
      commitment: 'Our Commitment to Your Privacy',
      commitmentText: 'We value your trust and are dedicated to protecting your personal information. We comply with all applicable data protection laws and follow industry best practices to keep your data secure.',

      section1: {
        title: '1. Information We Collect',
        content: 'We collect information that you provide directly to us when you use our services. This information is essential for processing your bookings and providing you with the best service.',
        point1: 'Personal identification information (name, email address, phone number) provided during booking',
        point2: 'Payment information necessary to process your bookings (processed securely through our payment partners)',
        point3: 'Booking history and travel preferences to improve your experience',
        point4: 'Technical information such as IP address, browser type, and device information for security and analytics',
      },

      section2: {
        title: '2. How We Use Your Information',
        content: 'We use the information we collect for specific purposes that enhance your experience and ensure smooth service delivery.',
        point1: 'To process and confirm your bus ticket bookings',
        point2: 'To communicate with you about your bookings, schedule changes, or service updates',
        point3: 'To provide customer support and respond to your inquiries',
        point4: 'To improve our services, website functionality, and user experience',
        point5: 'To detect and prevent fraud, unauthorized activities, and security threats',
      },

      section3: {
        title: '3. Information Sharing and Disclosure',
        content: 'We respect your privacy and do not sell your personal information. We only share your data in limited circumstances.',
        point1: 'With bus operators and service providers necessary to fulfill your booking',
        point2: 'With payment processors to handle your transactions securely',
        point3: 'When required by law, court order, or government regulations',
      },

      section4: {
        title: '4. Data Security',
        content: 'We implement robust security measures to protect your personal information from unauthorized access, alteration, or disclosure.',
        point1: 'Industry-standard encryption for data transmission and storage',
        point2: 'Secure payment processing through trusted and certified payment gateways',
        point3: 'Regular security audits and updates to protect against vulnerabilities',
        point4: 'Restricted access to personal information on a need-to-know basis',
      },

      section5: {
        title: '5. Your Rights and Choices',
        content: 'You have certain rights regarding your personal information and how we use it.',
        point1: 'Access and review your personal information by contacting our support team',
        point2: 'Request correction of inaccurate or incomplete information',
        point3: 'Request deletion of your personal data, subject to legal and contractual obligations',
      },

      section6: {
        title: '6. Cookies and Tracking',
        content: 'We use cookies and similar technologies to enhance your browsing experience and analyze website usage.',
        point1: 'Essential cookies required for website functionality and security',
        point2: 'Analytics cookies to understand how visitors use our website',
        point3: 'You can control cookie settings through your browser preferences',
      },

      contact: 'Contact Us About Privacy',
      contactText: 'If you have any questions or concerns about our Privacy Policy or how we handle your personal information, please contact us:',
      email: 'Email',
      phone: 'Phone',
    },

    refund: {
      title: 'Refund & Rescheduling Policy',
      mainTitle: 'Refund & Rescheduling Policy',
      mainDescription: 'Please read our refund and rescheduling policy carefully before making a booking. We offer flexible rescheduling options instead of cash refunds.',
      lastUpdated: 'Last Updated',

      noCashRefunds: 'No Cash Refunds',
      noCashRefundsText: 'Please note that we do not provide cash refunds for any bookings. However, you can reschedule your booking to another date and select different seats within the specified time period.',

      reschedulePolicy: 'Rescheduling Policy',
      reschedulePolicyDesc: 'We understand that plans can change. That\'s why we offer a flexible rescheduling option for your bookings.',

      whatYouCanDo: 'What You Can Do',
      canDo1: 'Cancel your existing booking within 7 days from the date you made the booking',
      canDo2: 'Reschedule to any available date and route',
      canDo3: 'Choose different seat numbers based on availability',

      importantTimeline: 'Important Timeline',
      within7Days: 'Within 7 Days',
      within7DaysDesc: 'You can cancel and reschedule your booking if you do so within 7 days from your booking date (not travel date). The 7-day period starts from the moment you completed your booking.',
      after7Days: 'After 7 Days',
      after7DaysDesc: 'Rescheduling requests made after 7 days from the booking date will not be accepted. Your booking becomes non-refundable and non-transferable.',

      howToRequest: 'How to Request Rescheduling',
      howToRequestDesc: 'Follow these simple steps to reschedule your booking:',

      step1Title: 'Contact Us',
      step1Desc: 'Call our customer support or send an email with your booking ID and the reason for rescheduling.',

      step2Title: 'Verify Your Booking',
      step2Desc: 'Provide your booking ID, phone number, and other details to verify your identity.',

      step3Title: 'Choose New Date & Seats',
      step3Desc: 'Select your preferred new travel date, route, and seat numbers based on availability.',

      step4Title: 'Confirmation',
      step4Desc: 'Once confirmed, you will receive a new booking confirmation with updated details.',

      importantNotes: 'Important Notes',
      note1: 'The 7-day period is calculated from your booking date, NOT from your travel date.',
      note2: 'Rescheduling is subject to seat availability on your chosen new date.',
      note3: 'You can only reschedule once. Multiple rescheduling requests are not permitted.',
      note4: 'The service fee paid during the original booking is non-refundable and will be applied to the rescheduled booking.',

      needHelp: 'Need Help with Rescheduling?',
      needHelpText: 'Our customer support team is here to assist you with rescheduling your booking. Contact us:',
      email: 'Email',
      phone: 'Phone',
      hours: 'Support Hours',
      hoursText: 'Monday - Sunday, 8:00 AM - 8:00 PM',
    },
  },
  si: {
    header: {
      home: 'මුල් පිටුව',
      about: 'අප ගැන',
      services: 'සේවාවන්',
      routes: 'මාර්ග',
      contact: 'අප හා සම්බන්ධ වන්න',
      bookNow: 'වෙන්කරවා ගන්න',
    },
    footer: {
      quickLinks: 'ඉක්මන් සබැඳි',
      followUs: 'අපව අනුගමනය කරන්න',
      allRightsReserved: 'සියලුම හිමිකම් ඇවිරිණි',
      privacyPolicy: 'රහස්‍යතා ප්‍රතිපත්තිය',
      terms: 'නියම සහ කොන්දේසි',
    },
    booking: {
      title: 'ඔබගේ ටිකට්පත වෙන්කරවා ගන්න',
      selectRoute: 'ඔබගේ මාර්ගය තෝරන්න',
      chooseJourney: 'ලබා ගත හැකි මාර්ග වලින් ඔබගේ ගමන තෝරන්න',
      selectBus: 'දිනය සහ විස්තර තෝරන්න',
      selectSeats: 'ඔබගේ ආසන තෝරන්න',
      passengerDetails: 'මගී විස්තර',
      travelDate: 'ගමන් දිනය',
      passengers: 'මගීන් සංඛ්‍යාව',
      passenger: 'මගීයෙකු',
      findYourRoute: 'ඔබගේ ගමන් මාර්ගය මෙතනින් තෝරාගන්න',
      selectLocations: 'ආරම්භක හා අවසන් වන ස්ථාන පහලින් තෝරාගන්න',
      passengers_plural: 'මගීන්',
      bookingHelp: 'උදව් අවශ්‍යද?',
      pickupLocation: 'ආරම්භක ස්ථානය',
      selectPickup: 'ආරම්භක ස්ථානය තෝරන්න',
      availableBuses: 'බස් රථය තෝරාගන්න',
      noBuses: 'මෙම මාර්ගයේ බස් රථ නොමැත',
      seats: 'ආසන',
      seat: 'ආසනය',
      back: 'ආපසු',
      departureSoon: 'ඉක්මනින් පිටත්වේ',
      continue: 'ඉදිරියට',
      bookingConfirmed: 'වෙන්කිරීම තහවුරු කරන ලදී!',
      bookingSuccess: 'ඔබගේ වෙන්කිරීම සාර්ථකව නිර්මාණය කර ඇත. කරුණාකර අනාගත යොමු කිරීම් සඳහා ඔබගේ වෙන්කිරීම් හැඳුනුම්පත සුරකින්න.',
      bookingId: 'වෙන්කිරීම් හැඳුනුම්පත',
      backToHome: 'මුල් පිටුවට',
      fullName: 'නම',
      enterFullName: 'ඔබගේ නම ඇතුළත් කරන්න',
      phoneNumber: 'දුරකථන අංකය',
      enterPhone: '+94 71 234 5678',
      email: 'විද්‍යුත් තැපෑල',
      enterEmail: 'your@email.com',
      optional: 'අත්‍යාවශ්‍ය නොවේ',
      confirmBooking: 'වෙන්කිරීම තහවුරු කරන්න',
      processing: 'ක්‍රියාත්මක වෙමින්...',
      route: 'මාර්ගය',
      bus: 'බස්',
      date: 'දිනය',
      totalAmount: 'මුළු මුදල',
      pricePerSeat: 'එක් ආසනයකට මිල',
      selectedSeats: 'තෝරාගත් ආසන',
      selectedBus: 'තෝරාගත් බස්',
      available: 'ලබා ගත හැකි',
      selected: 'තෝරාගත්',
      booked: 'වෙන්කර ඇත',
      driver: 'රියදුරු',
      selectionSummary: 'තෝරාගැනීමේ සාරාංශය',
      bookingSummary: 'වෙන්කිරීමේ සාරාංශය',
      bookingDetails: 'වෙන්කිරීමේ විස්තර',
      important: 'වැදගත්',
      arriveEarly: 'කරුණාකර පිටත්වීමට මිනිත්තු 15කට පෙර පැමිණෙන්න',
      carryId: 'තහවුරු කිරීම සඳහා දුරකතන අංකය හා SMS පනිවිඩය භාවිතා කරන්න',
      saveBookingId: 'යොමු කිරීම සඳහා ඔබගේ වෙන්කිරීමේ අංකය සුරකින්න',
      continueToSeats: 'ආසන තෝරාගැනීමට',
      continueToDetails: 'විස්තර වෙත',
      selectMoreSeats: 'තෝරන්න',
      moreSeats: 'තවත් ආසන තෝරන්න',
      pickupPoints: 'ආරම්භක ස්ථාන',
      minutes: 'මිනිත්තු',
      startingPoint: 'ආරම්භක ස්ථානය',
      fillAllFields: 'කරුණාකර අවශ්‍ය සියලුම ක්ෂේත්‍ර පුරවන්න',
      selectRouteFirst: 'කරුණාකර මුලින්ම මාර්ගයක් තෝරන්න',
      completeBusDetails: 'කරුණාකර මුලින්ම බස් සහ ගමන් විස්තර සම්පූර්ණ කරන්න',
      selectSeatsFirst: 'කරුණාකර මුලින්ම ඔබගේ ආසන තෝරන්න',
      onlySelect: 'ඔබට තෝරාගත හැක්කේ',
      failedFetchRoutes: 'මාර්ග ලබා ගැනීමට අසමත් විය',
      failedFetchBuses: 'බස් රථ ලබා ගැනීමට අසමත් විය',
      failedFetchSeats: 'ලබා ගත හැකි ආසන ලබා ගැනීමට අසමත් විය',
      bookingCreated: 'වෙන්කිරීම සාර්ථකව නිර්මාණය කරන ලදී!',
      failedCreateBooking: 'වෙන්කිරීම නිර්මාණය කිරීමට අසමත් විය',
      goToStep: 'පියවරට යන්න',
      completePrevious: 'කරුණාකර පෙර පියවර පළමුව සම්පූර්ණ කරන්න',
      seatLayout: 'ආසන සැලසුම',
      bookYourBusTicket: 'ඔබගේ බස් ටිකට්පත වෙන්කරවා ගන්න',
      from: 'සිට',
      to: 'දක්වා',
      searchBuses: 'බස් සොයන්න',
      popularRoutes: 'ජනප්‍රිය මාර්ග',
      departsIn: 'පිටත්වේ',
      min: 'මිනි',
      notSet: 'සකසා නැත',
      routeComingSoon: 'මෙම මාර්ගය ළඟදීම එන අතර තවමත් වෙන්කිරීම සඳහා ලබා ගත නොහැක',
      routeComingSoonDesc: 'කරුණාකර පසුව නැවත පරීක්ෂා කරන්න හෝ වෙනත් මාර්ගයක් තෝරන්න',
      routeSelected: 'මාර්ගය තෝරාගන්නා ලදී',
      locked: 'අගුළු දමා ඇත',
      noneSelected: 'තෝරාගෙන නැත',
      subtotal: 'උප එකතුව',
      lkr: 'රු',
      perSeat: 'එක් ආසනයකට',
      serviceFee: 'සේවා ගාස්තුව',
      more: 'තවත්',
      comingSoon: 'ඉදිරියේදී ආරම්භ වේ',
      notAvailableYet: 'තවමත් වෙන්කිරීම සඳහා ලබා ගත නොහැක',
      howToBook: 'ඔබගේ ටිකට්පත වෙන්කරවා ගන්නේ කෙසේද',
      followSteps: 'ඔබගේ වෙන්කිරීම සම්පූර්ණ කිරීමට මෙම සරල පියවර අනුගමනය කරන්න',
      step: 'පියවර',
      searchRoute: 'මාර්ගය සොයන්න',
      searchRouteDesc: 'ලබා ගත හැකි මාර්ග සොයා ගැනීමට ඔබගේ පිටත්වීමේ සහ ගමනාන්ත ස්ථාන තෝරන්න',
      selectSeatsTitle: 'ආසන තෝරන්න',
      selectSeatsDesc: 'ඔබගේ කැමති බස්, ගමන් දිනය තෝරා ගන්න සහ සැලැස්මෙන් ඔබගේ ආසන තෝරන්න',
      confirmBookingTitle: 'වෙන්කිරීම තහවුරු කරන්න',
      confirmBookingDesc: 'ඔබගේ විස්තර ඇතුළත් කර ඔබගේ ටිකට්පත ලබා ගැනීමට වෙන්කිරීම තහවුරු කරන්න',
      note: 'සටහන',
      serviceFeeNote: 'සේවා ගාස්තුවක්',
      findRouteInstantly: 'ඔබගේ මාර්ගය ක්ෂණිකව සොයා ගන්න',
      selectJourneyDetails: 'ලබා ගත හැකි ගමන් බැලීමට පහත ඔබගේ ගමන් විස්තර තෝරන්න',
      departureLocation: 'පිටත්වීමේ ස්ථානය',
      whereLeaving: 'ඔබ පිටත්වන්නේ කොහෙන්ද?',
      allLocations: 'සියලුම ස්ථාන',
      arrivalLocation: 'පැමිණෙන ස්ථානය',
      whereGoing: 'ඔබ යන්නේ කොහෙටද?',
      allDestinations: 'සියලුම ගමනාන්ත',
      clearFilters: 'පෙරහන් ඉවත් කරන්න',
      routeFound: 'මාර්ගය හමු විය',
      routesFound: 'මාර්ග හමු විය',
      noRoutesFound: 'මාර්ග හමු නොවීය',
      noRoutesFoundDesc: 'තෝරාගත් ස්ථාන සඳහා මාර්ග නොමැත',
      selectBusDesc: 'ඔබගේ බස් සහ ගමන් දිනය තෝරන්න',
      selectedRoute: 'තෝරාගත් මාර්ගය',
      tripDetails: 'ගමන් විස්තර',
      choosePreferredSeats: 'ඔබගේ කැමති ආසන තෝරන්න',
      enterContactInfo: 'වෙන්කිරීම සම්පූර්ණ කිරීමට ඔබගේ සම්බන්ධතා තොරතුරු ඇතුළත් කරන්න',
      contactInformation: 'සම්බන්ධතා තොරතුරු',
    },
    common: {
      welcome: 'සාදරයෙන් පිළිගනිමු',
      loading: 'පූරණය වෙමින්...',
      error: 'දෝෂයකි',
      success: 'සාර්ථකයි',
      backToHome: 'මුල් පිටුවට',
      cancel: 'අවලංගු කරන්න',
      confirm: 'තහවුරු කරන්න',
      close: 'වසන්න',
    },
    hero: {
      title: {
        line1: 'ඔබේ ගමන',
        line2: 'මෙතැනින් ආරම්භ වේ'
      },
      description: 'ශ්‍රී ලංකාව පුරා සුවපහසු, ආරක්ෂිත සහ විශ්වාසදායක බස් ගමන අත්දැකීම ලබා ගන්න.',
      bookButton: 'ඔබගේ ආසනය වෙන්කරවා ගන්න',
      imageAlt: {
        mountains: 'කඳු හරහා ශ්‍රී ලංකික බස් ගමන',
        interior: 'සුවපහසු බස් අභ්‍යන්තරය',
        landscape: 'ලස්සන ශ්‍රී ලංකික භූ දර්ශනය',
        mountainsMobile: 'කඳු හරහා ශ්‍රී ලංකික බස් ගමන - ජංගම දර්ශනය',
        interiorMobile: 'සුවපහසු බස් අභ්‍යන්තරය - ජංගම දර්ශනය',
        landscapeMobile: 'ලස්සන භූ දර්ශනය - ජංගම දර්ශනය'
      }
    },
    about: {
      title: 'ඔබගේ විශ්වාසදායක ගමන් සහකරු',
      since: '1995 සිට',
      subtitle: 'ශ්‍රී ලංකාවේ සුන්දර දිවයින පුරා හදවත්, ගමනාන්ත සහ සිහින සම්බන්ධ කරමින් ආරක්ෂිත, සුවපහසු සහ විශ්වාසදායක ප්‍රවාහන සේවා සපයයි.',
      ourStory: 'අප ගැන',
      storyParagraph1: 'bus Seat Booking වෙත සාදරයෙන් පිළිගනිමු! පහසු සහ විශ්වාසනීය බස් ටිකට්පත් වෙන්කරවා ගැනීම සඳහා වන ඔබේ හිතවත්ම සහකරු අපයි. ඔබගේ ගමනාන්ත වෙත බස් ආසන සෙවීමට, සැසඳීමට සහ වෙන්කරවා ගැනීමට ඇති බාධාවකින් තොර, එකම වේදිකාවක් සපයමින් ඔබගේ සංචාරක කටයුතු සරල කිරීමට අපි කැපවී සිටිමු. අපගේ මෙහෙවර වන්නේ බස් ගමන් බිමන් සැමට වඩාත් පහසුවෙන් ප්‍රවේශ විය හැකි සහ සරල අත්දැකීමක් බවට පත් කිරීමයි. සෑම අයවැයකටම සහ සුවපහසු මට්ටමකටම ගැලපෙන පරිදි පුළුල් පරාසයක බස් මාර්ග, කාලසටහන් සහ බස් රථ වර්ග පිරිනමමින්, අපි ඔබව විශාල බස් ක්‍රියාකරුවන්ගේ ජාලයක් සමඟ සම්බන්ධ කරමු.',
      storyParagraph2: 'ඔබ දෛනික ගමනක්, සති අන්තයේ විනෝද චාරිකාවක් හෝ දුර ගමනක් සැලසුම් කළත්, අපගේ පරිශීලක-හිතකාමී වෙබ් අඩවිය ඔස්සේ ඕනෑම වේලාවක, ඕනෑම තැනක සිට ක්ලික් කිරීම් කිහිපයකින් ඔබේ ටිකට් පත් වෙන්කරවා ගත හැකි බවට අපි සහතික වෙමු. ආරක්ෂිත ගමන්, විනිවිද පෙනෙන මිල ගණන් සහ කැපවූ පාරිභෝගික සහාය අපි විශ්වාස කරමු. ඔබගේ ගමනාන්තය කරා ළඟා වීමට අපව තෝරා ගැනීම පිළිබඳව ඔබට ස්තූතියි.',
      islandWideCoverage: 'දිවයින පුරා ආවරණය',
      coverageDescription: 'සියලුම ප්‍රධාන නගර සහ නගර සම්බන්ධ කිරීම',
      onTimeRate: 'නියමිත කාලයට',
      customerRating: 'පාරිභෝගික ශ්‍රේණිගත කිරීම',
      trustedBy: 'ශ්‍රී ලංකාව පුරා දහස් ගණනක් විසින් විශ්වාසය',
      numbersSpeak: 'අපගේ විශිෂ්ටත්වයට කැපවීම ගැන කතා කරන සංඛ්‍යා',
      happyPassengers: 'සතුටු මගීන්',
      routesCovered: 'ආවරණය කළ මාර්ග',
      modernBuses: 'නවීන බස් රථ',
      yearsExperience: 'වසර අත්දැකීම්',
      bookNextTrip: 'විශ්වාසයෙන් ඔබගේ ඊළඟ ගමන වෙන්කරවා ගන්න',
      swipeToStart: 'ඔබගේ ගමන ආරම්භ කිරීමට ස්වයිප් කරන්න',
      redirecting: 'හරවා යවමින්...',
      experience25Years: 'වසර 25+ අත්දැකීම්',
      experience25YearsDesc: '1995 සිට විශිෂ්ටත්වයෙන් ශ්‍රී ලංකාවට සේවය කිරීම, විශ්වාසදායක සේවාව හරහා විශ්වාසය ගොඩනැගීම',
      happyCustomers1M: 'මිලියන 1+ සතුටු ගනුදෙනුකරුවන්',
      happyCustomers1MDesc: 'ජාතික වශයෙන් මගීන් මිලියන ගණනකගේ විශ්වාසය 98% තෘප්තිමත් අනුපාතයකින්',
      safetyRecord100: '100% ආරක්ෂිත වාර්තාව',
      safetyRecord100Desc: 'පසුගිය වසර 5 තුළ හදිසි අනතුරු ශුන්‍ය සමඟ ඉහළම ආරක්ෂිත ප්‍රමිතීන් පවත්වා ගැනීම',
      service247: '24/7 සේවාව',
      service247Desc: 'පැය 24 පාරිභෝගික සහාය සහ හදිසි ආධාර ලබා ගත හැකිය',
    },
    services: {
      title: 'අපගේ වාරික සේවා',
      subtitle: 'ශ්‍රී ලංකාව පුරා ඔබගේ ගමන සුවපහසු සහ අමතක නොවන ලෙස සැලසුම් කර ඇති ලෝක මට්ටමේ පහසුකම් සහ සේවා අත්විඳින්න.',
      luxuryBuses: 'සුඛෝපභෝගී බස් රථ',
      luxuryBusesDesc: 'අත්‍යවශ්‍ය ගමන් අත්දැකීම සඳහා පසුපසට නැමිය හැකි ආසන සහ ප්‍රමාණවත් කකුල් ඉඩ සහිත නවීන, සුවපහසු බස් රථ',
      safeTravel: 'ආරක්ෂිත ගමන',
      safeTravelDesc: 'අත්දැකීම් සහිත රියදුරන් සහ ඔබගේ ආරක්ෂාව සඳහා නිතිපතා වාහන නඩත්තුව 24/7 අධීක්ෂණ පද්ධති සමඟ',
      airConditioning: 'වායු සමීකරණය',
      airConditioningDesc: 'සියලුම කාලගුණික තත්වයන් තුළ සුවපහසු ගමන සඳහා දේශගුණ පාලන පරිසරය',
      learnMore: 'වැඩි විස්තර',
      readyToExperience: 'වාරික ගමන අත්විඳීමට සූදානම්ද?',
      readyToExperienceDesc: 'අද ඔබගේ ගමන වෙන්කරවා ගන්න සහ සෑම ගමනක්ම සුවපහසු සහ ආරක්ෂිත අත්දැකීමක් බවට පත් කරන අපගේ ලෝක මට්ටමේ සේවා භුක්ති විඳින්න.',
      bookYourTrip: 'ඔබගේ ගමන වෙන්කරවා ගන්න',
      viewAllRoutes: 'සියලුම මාර්ග බලන්න',
    },
    routes: {
      title: 'ජනප්‍රිය',
      titleHighlight: 'මාර්ග',
      subtitle: 'අපගේ වඩාත්ම ගමන් කරන මාර්ග වලින් තෝරා ගෙන වාරික සුවපහසුව අත්විඳින්න',
      loadingRoutes: 'මාර්ග පූරණය වෙමින්...',
      noRoutesAvailable: 'මාර්ග නොමැත',
      checkBackLater: 'ලබා ගත හැකි මාර්ග සඳහා පසුව නැවත පරීක්ෂා කරන්න.',
      duration: 'කාලය',
      distance: 'දුර',
      pickupPoints: 'ආරම්භක ස්ථාන',
      more: 'තවත්',
      bookThisRoute: 'මෙම මාර්ගය වෙන්කරවා ගන්න',
      exploreAllRoutes: 'සියලුම මාර්ග ගවේෂණය කරන්න',
      startingFrom: 'සිට ආරම්භ වේ',
    },
    contact: {
      title: 'අප හා සම්බන්ධ වන්න',
      subtitle: 'ප්‍රශ්න හෝ සහාය අවශ්‍යද? අපගේ මිත්‍රශීලී කණ්ඩායම ඔබගේ පරිපූර්ණ ගමන සැලසුම් කිරීමට ඔබට උදව් කිරීමට සූදානම්.',
      contactInformation: 'සම්බන්ධතා තොරතුරු',
      headOffice: 'ප්‍රධාන කාර්යාලය',
      headOfficeAddress: '123 ප්‍රධාන වීදිය, කොළඹ 07\nශ්‍රී ලංකාව',
      phoneNumbers: 'දුරකථන අංක',
      hotline: 'හොට්ලයින්',
      mobile: 'ජංගම',
      email: 'විද්‍යුත් තැපෑල',
      officeHours: 'කාර්යාල වේලාවන්',
      officeHoursWeekday: 'සඳුදා - සෙනසුරාදා: පෙ.ව. 6:00 - ප.ව. 10:00',
      officeHoursSunday: 'ඉරිදා: පෙ.ව. 7:00 - ප.ව. 9:00',
      mapComingSoon: 'අන්තර්ක්‍රියාකාරී සිතියම ළඟදීම එනවා',
      sendMessage: 'අපට පණිවිඩයක් යවන්න',
      firstName: 'මුල් නම',
      firstNamePlaceholder: 'ඔබගේ මුල් නම',
      lastName: 'අවසාන නම',
      lastNamePlaceholder: 'ඔබගේ අවසාන නම',
      emailAddress: 'විද්‍යුත් තැපැල් ලිපිනය',
      emailPlaceholder: 'your.email@example.com',
      phoneNumber: 'දුරකථන අංකය',
      phonePlaceholder: '+94 XX XXX XXXX',
      subject: 'විෂයය',
      selectSubject: 'විෂයයක් තෝරන්න',
      bookingInquiry: 'වෙන්කිරීම් විමසීම',
      complaint: 'පැමිණිල්ල',
      suggestion: 'යෝජනාව',
      other: 'වෙනත්',
      message: 'පණිවිඩය',
      messagePlaceholder: 'අපට ඔබට උදව් කළ හැකි ආකාරය අපට කියන්න...',
      sendMessageButton: 'පණිවිඩය යවන්න',
    },
    faq: {
      title: 'නිතර අසන ප්‍රශ්න',
      subtitle: 'අපගේ සේවා, වෙන්කිරීමේ ක්‍රියාවලිය සහ ගමන් ප්‍රතිපත්ති පිළිබඳ පොදු ප්‍රශ්නවලට පිළිතුරු සොයා ගන්න.',
      stillHaveQuestions: 'තවමත් ප්‍රශ්න තිබේද? අපි උදව් කිරීමට මෙහි සිටිමු!',
      contactSupport: 'සහාය අමතන්න',
      question1: 'Bus Seat Booking සමඟ බස් ටිකට්පතක් වෙන්කරවා ගන්නේ කෙසේද?',
      answer1: 'ඔබට අපගේ වෙබ් අඩවිය හරහා ඔන්ලයින් ටිකට් වෙන්කරවා ගත හැකිය. ඔන්ලයින් වෙන්කිරීම 24/7 ලබා ගත හැකි අතර ක්ෂණික තහවුරු කිරීමක් ලබා දෙයි.',
      question2: 'ඔබගේ අවලංගු කිරීමේ සහ ආපසු ගෙවීමේ ප්‍රතිපත්තිය කුමක්ද?',
      answer2: 'පිටත්වීමට පැය 24කට පෙර කරන ලද අවලංගු කිරීම් සඳහා සැකසුම් ගාස්තුව අඩු කර සම්පූර්ණ ආපසු ගෙවීමක් ලැබෙනු ඇත. පැය 24 ඇතුළත අවලංගු කිරීම් 25% අඩු කිරීමකට යටත් වේ. පැමිණීමට අසමත් වීම් සඳහා ආපසු ගෙවීමක් නැත.',
      question3: 'ඔබගේ බස් රථ වායු සමීකරණ සහිතද?',
      answer3: 'ඔව්, අපගේ සියලුම බස් රථ නවීන වායු සමීකරණ පද්ධති වලින් සමන්විත වේ. වාරික සුවපහසුව සඳහා පුද්ගලික දේශගුණ පාලන සහිත සුඛෝපභෝගී බස් රථ ද අප සතුවේ.',
      question4: 'ඔබට ස්ථාපිත ආරක්ෂිත පියවර මොනවාද?',
      answer4: 'අපි නිතිපතා වාහන නඩත්තුව, GPS ලුහුබැඳීම, පුහුණු රියදුරන්, ප්‍රථමාධාර කට්ටල සහ සියලුම ගමන් වල 24/7 අධීක්ෂණය ඇතුළුව දැඩි ආරක්ෂිත ප්‍රොටෝකෝල පවත්වා ගනිමු.',
      question5: 'වෙන්කිරීමේදී මගේ ආසනය තෝරා ගත හැකිද?',
      answer5: 'ඔව්, අපගේ ඔන්ලයින් වෙන්කිරීම් පද්ධතිය ඔබට ලබා ගත හැකි විකල්ප වලින් ඔබගේ කැමති ආසනය තෝරා ගැනීමට ඉඩ සලසයි. වාරික ආසන කුඩා අතිරේක වියදමකින් ලබා ගත හැකිය.',
      question6: 'දිගු ගමන් වලදී ඔබ ආහාර සපයනවාද?',
      answer6: 'පැය 6කට වැඩි මාර්ග වලදී, අපි නොමිලේ සුලු ආහාර සහ ප්‍රණීත පාන සපයනු ලබමු. පැය 8කට වැඩි ගමන් සඳහා ආහාර නැවතුම් සැලසුම් කර ඇත.',
      question7: 'මගේ බස් රථය ප්‍රමාද වුවහොත් හෝ අවලංගු වුවහොත් කුමක් වේද?',
      answer7: 'ප්‍රමාද වූ අවස්ථාවේ දී, අපි SMS/විද්‍යුත් තැපෑල හරහා මගීන්ට දැනුම් දෙමු. අවලංගු කිරීම් සඳහා, අපි විකල්ප ප්‍රවාහනය සංවිධානය කරන්නෙමු හෝ සම්පූර්ණ ආපසු ගෙවීම සපයමු. සැලකිය යුතු ප්‍රමාද සඳහා වන්දි අදාළ විය හැකිය.',
      question8: 'බස් රථ වල WiFi ලබා ගත හැකිද?',
      answer8: 'ඔව්, අපගේ බොහෝ බස් රථ නොමිලේ WiFi ලබා දෙයි. සුඛෝපභෝගී මාර්ග වලදී චිත්‍රපට, සංගීතය සහ ක්‍රීඩා සහිත විනෝදාස්වාද පද්ධති ලබා ගත හැකිය.',
    },
    whyChooseUs: {
      title: 'අපගේ සේවාව තෝරාගන්නෙ ඇයි?',
      subtitle: 'අපි බස් සේවාවක් පමණක් නොව - අපි ඔබගේ ගමන් සහකරු වන අතර සෑම ගමනක්ම ආරක්ෂිත, සුවපහසු සහ අමතක නොවන ලෙස කැපවී සිටිමු.',
      safetyFirst: 'ආරක්ෂාව පළමුව',
      safetyFirstDesc: 'අපගේ ප්‍රමුඛතාවය ඔබගේ ආරක්ෂාවයි. අපගේ සියලුම බස් රථ නිතිපතා නඩත්තුවට යටත් වන අතර අපගේ රියදුරන් සම්පූර්ණයෙන්ම පුහුණු සහ අත්දැකීම් ඇත.',
      onTimeGuarantee: 'නියමිත කාලයට සහතිකය',
      onTimeGuaranteeDesc: 'අපි ඔබගේ කාලය අගය කරමු. අපගේ බස් රථ දැඩි කාලසටහන් අනුගමනය කරන අතර අපි නියමිත වේලාවට පිටත්වීම් සහ පැමිණීම් සහතික කරමු.',
      bestPrices: 'හොඳම මිල ගණන්',
      bestPricesDesc: 'ගුණාත්මකභාවයට සම්මුතියක් නොකර තරඟකාරී මිල ගණන් භුක්ති විඳින්න. අපි ශ්‍රී ලංකාවේ මුදලට හොඳම වටිනාකම ලබා දෙමු.',
      support247: '24/7 සහාය',
      support247Desc: 'වෙන්කිරීම්, විමසීම් සහ සහාය සමඟ ඔබට උදව් කිරීමට අපගේ පාරිභෝගික සේවා කණ්ඩායම පැය 24ම ලබා ගත හැකිය.',
      awardWinning: 'සම්මාන ලද',
      awardWinningDesc: 'ජාතික ප්‍රවාහන මණ්ඩලය විසින් අඛණ්ඩව වසර තුනක් ශ්‍රී ලංකාවේ හොඳම බස් සේවා සපයන්නා ලෙස පිළිගැනීමට ලක් විය.',
      trustedByMillions: 'මිලියන ගණනක් විශ්වාසය',
      trustedByMillionsDesc: 'තෘප්තිමත් පාරිභෝගිකයින් මිලියනයකට වැඩි ප්‍රමාණයක් ඔවුන්ගේ ගමන් අවශ්‍යතා සඳහා අපව තෝරා ගෙන ඇත. සතුටු සංචාරකයින්ගේ අපගේ පවුලට එකතු වන්න.',
      readyToExperience: 'වෙනස අත්විඳීමට සූදානම්ද?',
      readyToExperienceDesc: 'ඔවුන්ගේ ගමන සඳහා Bus Seat Booking විශ්වාස කරන දහස් ගණන් තෘප්තිමත් පාරිභෝගිකයින් සමඟ එකතු වන්න',
      bookYourTrip: 'ඔබගේ ගමන වෙන්කරවා ගන්න',
      contactUs: 'අප හා සම්බන්ධ වන්න',
    },
    terms: {
      title: 'නියම සහ කොන්දේසි',
      mainTitle: 'නියම සහ කොන්දේසි',
      mainDescription: 'අපගේ බස් වෙන්කිරීමේ සේවාව භාවිතා කිරීමට පෙර කරුණාකර මෙම නියම සහ කොන්දේසි ප්‍රවේශමෙන් කියවන්න. ප්‍රවේශ පත්‍රයක් වෙන්කරවා ගැනීමෙන්, ඔබ මෙම නියමයන්ට බැඳී සිටීමට එකඟ වේ.',
      lastUpdated: 'අවසන් යාවත්කාලීනය',
      importantNotice: 'වැදගත් දැනුම්දීම',
      importantNoticeText: 'අපගේ වෙන්කිරීමේ සේවාව භාවිතා කිරීමෙන් සහ වෙන්කිරීමක් කිරීමෙන්, ඔබ මෙම නියම සහ කොන්දේසි කියවා, තේරුම් ගෙන, ඒවාට බැඳී සිටීමට එකඟ වන බව ඔබ පිළිගනී. ඔබ මෙම නියමවල කිසියම් කොටසක් සමඟ එකඟ නොවන්නේ නම්, කරුණාකර අපගේ සේවාව භාවිතා නොකරන්න.',

      section1: {
        title: '1. සාමාන්‍ය සේවා නියම',
        content: 'මෙම නියම අපගේ ඔන්ලයින් බස් වෙන්කිරීමේ වේදිකාව සහ සේවා භාවිතා කිරීම පාලනය කරයි. අපගේ වේදිකාව හරහා කරන ලද සියලුම වෙන්කිරීම් මෙම නියම සහ කොන්දේසි වලට යටත් වේ.',
        point1: 'සියලුම පරිශීලකයින්ට වයස අවුරුදු 18 හෝ ඊට වැඩි විය යුතුය, නැතහොත් මාපිය/භාරකරුවන්ගේ අවසරය තිබිය යුතුය.',
        point2: 'වෙන්කිරීමේ ක්‍රියාවලියේදී නිවැරදි, වත්මන් සහ සම්පූර්ණ තොරතුරු ලබා දීමට ඔබ එකඟ වේ.',
        point3: 'ඔබගේ වෙන්කිරීමේ තොරතුරු රහස්‍යභාවය පවත්වා ගැනීම සඳහා ඔබ වගකිව යුතුය.',
        point4: 'මෙම නියම උල්ලංඝනය කරන සේවාව ප්‍රතික්ෂේප කිරීමට හෝ වෙන්කිරීම් අවලංගු කිරීමට අපට අයිතිය ඇත.',
      },

      section2: {
        title: '2. වෙන්කිරීම් සහ ගෙවීම් නියම',
        content: 'සියලුම වෙන්කිරීම් අපගේ ආරක්ෂිත ගෙවීම් ද්වාරය හරහා ඔන්ලයින් සම්පූර්ණ කළ යුතුය. ඔබගේ වෙන්කිරීම තහවුරු කිරීම සඳහා වෙන්කිරීමේ අවස්ථාවේදීම ගෙවීම අවශ්‍ය වේ.',
        point1: 'සියලුම මිල ශ්‍රී ලංකා රුපියල් (LKR) වලින් ප්‍රදර්ශනය කර ඇති අතර වෙනත් ආකාරයකින් සඳහන් නොකළ හොත් අදාළ බදු ඇතුළත් වේ.',
        point2: 'මෙහෙයුම් වියදම් ආවරණය කිරීම සඳහා වෙන්කිරීමකට ආපසු ගෙවිය නොහැකි සේවා ගාස්තුවක් අය කරනු ලැබේ.',
        point3: 'සැසි කාලය තුළ ගෙවීම සම්පූර්ණ කළ යුතුය, නැතහොත් තෝරාගත් ආසන මුදා හරිනු ලැබේ.',
        point4: 'අපගේ ආරක්ෂිත ගෙවීම් හවුල්කරු හරහා අපි ප්‍රධාන ණය කාඩ්පත්, ඩෙබිට් කාඩ්පත් සහ ඩිජිටල් ගෙවීම් ක්‍රම භාගත් කරමු.',
        point5: 'ගෙවීම තහවුරු වූ පසු, ඔබට අනන්‍ය වෙන්කිරීමේ ID සහිත වෙන්කිරීමේ තහවුරුවක් ලැබෙනු ඇත.',
      },

      section3: {
        title: '3. අවලංගු කිරීම් සහ ආපසු ගෙවීම් ප්‍රතිපත්තිය',
        content: 'අවලංගු කිරීම් අපගේ ආපසු ගෙවීම් ප්‍රතිපත්තියට යටත් වේ. වෙන්කිරීමක් කිරීමට පෙර කරුණාකර ප්‍රවේශමෙන් කියවන්න.',
        point1: 'පිටත්වීමේ වේලාවට පැය 24කට හෝ ඊට වැඩි කාලයකට පෙර අවලංගු කිරීම්: 80% ආපසු ගෙවීම (සේවා ගාස්තුව ආපසු නොගෙවනු ලැබේ).',
        point2: 'පිටත්වීමට පැය 12-24 අතර අවලංගු කිරීම්: 50% ආපසු ගෙවීම (සේවා ගාස්තුව ආපසු නොගෙවනු ලැබේ).',
        point3: 'පිටත්වීමට පැය 12කට අඩු කාලයකට පෙර අවලංගු කිරීම්: ආපසු ගෙවීමක් නැත.',
        point4: 'ආපසු ගෙවීම් මුල් ගෙවීම් ක්‍රමයට ව්‍යාපාර දින 7-10ක් ඇතුළත සකසනු ලැබේ.',
      },

      section4: {
        title: '4. මගී වගකීම්',
        content: 'මගියෙකු ලෙස, ඔබ පහත වගකීම් සහ අවශ්‍යතා සපුරාලීම අවශ්‍ය වේ.',
        point1: 'නියමිත පිටත්වීමේ වේලාවට අවම වශයෙන් මිනිත්තු 15කට පෙර නියම කළ රැගෙන යාමේ ස්ථානයට පැමිණෙන්න.',
        point2: 'සත්‍යාපන කටයුතු සඳහා වලංගු රජයේ නිකුත් කළ ඡායාරූප හැඳුනුම්පතක් රැගෙන යන්න.',
        point3: 'සුදුසු හැසිරීමක් පවත්වා ගෙන අනෙකුත් මගීන්ට සහ බස් කාර්ය මණ්ඩලයට ගරු කරන්න.',
        point4: 'බස් රථයේ දුම්පානය, මත්පැන් පානය හෝ නීති විරෝධී ක්‍රියාකාරකම්වලට අවසර නැත.',
      },

      section5: {
        title: '5. වගකීම් සීමා කිරීම්',
        content: 'අපගේ වගකීම පහතින් දක්වා ඇති පරිදි සීමා කර ඇත. කරුණාකර මෙම සීමාවන් ප්‍රවේශමෙන් කියවන්න.',
        point1: 'කාලගුණය, ගමනාගමනය, යාන්ත්‍රික ගැටළු හෝ අපගේ පාලනයෙන් ඔබ්බෙන් වන වෙනත් තත්වයන් හේතුවෙන් ප්‍රමාදයන්, අවලංගු කිරීම් හෝ මාර්ග වෙනස් කිරීම් සඳහා අපි වගකිව යුතු නොවේ.',
        point2: 'මගීන් ඔවුන්ගේ පෞද්ගලික බඩු බාහිරාදිය සඳහා වගකිව යුතුය. අහිමි වූ, සොරකම් කළ හෝ හානි වූ භාණ්ඩ සඳහා අපි වගකිව යුතු නොවේ.',
        point3: 'ඕනෑම හිමිකම් පෑමක් සඳහා අපගේ උපරිම වගකීම මගියා විසින් ගෙවන ලද ප්‍රවේශ පත්‍ර මිලින් ඉක්මවිය නොහැක.',
      },

      section6: {
        title: '6. රහස්‍යතාව සහ දත්ත ආරක්ෂණය',
        content: 'ඔබගේ පුද්ගලික තොරතුරු සහ රහස්‍යතාව ආරක්ෂා කිරීමට අපි කැපවී සිටිමු.',
        point1: 'වෙන්කිරීමේ අවස්ථාවේදී එකතු කරන ලද පුද්ගලික තොරතුරු සේවා බෙදාහැරීම සහ සන්නිවේදනය සඳහා පමණක් භාවිතා වේ.',
        point2: 'ගෙවීම් සැකසීම සඳහා අවශ්‍ය විට හැර අපි ඔබගේ පුද්ගලික දත්ත තුන්වන පාර්ශ්වයන් සමඟ විකිණීම හෝ බෙදා ගැනීම නොකරමු.',
        point3: 'වැඩි විස්තර සඳහා, කරුණාකර අපගේ රහස්‍යතා ප්‍රතිපත්ති පිටුව බලන්න.',
      },

      questions: 'ප්‍රශ්න හෝ කනස්සල්ලද?',
      questionsText: 'මෙම නියම සහ කොන්දේසි පිළිබඳව ඔබට කිසියම් ප්‍රශ්නයක් ඇත්නම්, කරුණාකර අප හා සම්බන්ධ වන්න:',
      email: 'විද්‍යුත් තැපෑල',
      phone: 'දුරකථන',
    },

    // PRIVACY POLICY SINHALA TRANSLATIONS
    privacy: {
      title: 'රහස්‍යතා ප්‍රතිපත්තිය',
      mainTitle: 'රහස්‍යතා ප්‍රතිපත්තිය',
      mainDescription: 'ඔබේ රහස්‍යතාව සහ පුද්ගලික තොරතුරු ආරක්ෂා කිරීමට අපි කැපවී සිටිමු. ඔබ අපගේ බස් වෙන්කිරීමේ සේවාව භාවිතා කරන විට අපි ඔබේ දත්ත එකතු කරන, භාවිතා කරන සහ ආරක්ෂා කරන ආකාරය මෙම ප්‍රතිපත්තිය පැහැදිලි කරයි.',
      lastUpdated: 'අවසන් යාවත්කාලීනය',
      commitment: 'ඔබේ රහස්‍යතාවයට අපගේ කැපවීම',
      commitmentText: 'අපි ඔබගේ විශ්වාසය අගය කරන අතර ඔබගේ පුද්ගලික තොරතුරු ආරක්ෂා කිරීමට කැපවී සිටිමු. අපි අදාළ සියලුම දත්ත ආරක්ෂණ නීතිවලට අනුකූල වන අතර ඔබගේ දත්ත ආරක්ෂිතව තබා ගැනීම සඳහා කර්මාන්තයේ හොඳම භාවිතයන් අනුගමනය කරමු.',

      section1: {
        title: '1. අපි එකතු කරන තොරතුරු',
        content: 'ඔබ අපගේ සේවා භාවිතා කරන විට ඔබ සෘජුවම අපට සපයන තොරතුරු අපි එකතු කරමු. මෙම තොරතුරු ඔබගේ වෙන්කිරීම් සැකසීම සහ ඔබට හොඳම සේවාව ලබා දීම සඳහා අත්‍යවශ්‍ය වේ.',
        point1: 'වෙන්කිරීමේ අවස්ථාවේදී සපයන ලද පුද්ගලික හඳුනාගැනීමේ තොරතුරු (නම, විද්‍යුත් තැපැල් ලිපිනය, දුරකථන අංකය)',
        point2: 'ඔබගේ වෙන්කිරීම් සැකසීමට අවශ්‍ය ගෙවීම් තොරතුරු (අපගේ ගෙවීම් හවුල්කරුවන් හරහා ආරක්ෂිතව සකසනු ලැබේ)',
        point3: 'ඔබගේ අත්දැකීම වැඩිදියුණු කිරීම සඳහා වෙන්කිරීම් ඉතිහාසය සහ ගමන් මනාපයන්',
        point4: 'ආරක්ෂාව සහ විශ්ලේෂණ සඳහා IP ලිපිනය, බ්‍රව්සර් වර්ගය සහ උපකරණ තොරතුරු වැනි තාක්ෂණික තොරතුරු',
      },

      section2: {
        title: '2. අපි ඔබගේ තොරතුරු භාවිතා කරන ආකාරය',
        content: 'ඔබගේ අත්දැකීම වැඩිදියුණු කරන සහ සුමට සේවා බෙදා හැරීම සහතික කරන නිශ්චිත අරමුණු සඳහා අපි එකතු කරන තොරතුරු භාවිතා කරමු.',
        point1: 'ඔබගේ බස් ප්‍රවේශ පත්‍ර වෙන්කිරීම් සැකසීමට සහ තහවුරු කිරීමට',
        point2: 'ඔබගේ වෙන්කිරීම්, කාලසටහන් වෙනස්කම් හෝ සේවා යාවත්කාලීන පිළිබඳව ඔබ සමඟ සන්නිවේදනය කිරීමට',
        point3: 'පාරිභෝගික සහාය ලබා දීමට සහ ඔබගේ විමසීම්වලට ප්‍රතිචාර දැක්වීමට',
        point4: 'අපගේ සේවා, වෙබ් අඩවි ක්‍රියාකාරිත්වය සහ පරිශීලක අත්දැකීම් වැඩිදියුණු කිරීමට',
        point5: 'වංචා, අනවසර ක්‍රියාකාරකම් සහ ආරක්ෂක තර්ජන හඳුනා ගැනීමට සහ වැලැක්වීමට',
      },

      section3: {
        title: '3. තොරතුරු බෙදා ගැනීම සහ හෙළිදරව් කිරීම',
        content: 'අපි ඔබගේ රහස්‍යතාවයට ගරු කරන අතර ඔබගේ පුද්ගලික තොරතුරු විකිණීම නොකරමු. සීමිත තත්වයන් තුළ පමණක් අපි ඔබගේ දත්ත බෙදා ගනිමු.',
        point1: 'ඔබගේ වෙන්කිරීම සම්පූර්ණ කිරීමට අවශ්‍ය බස් ක්‍රියාකරුවන් සහ සේවා සපයන්නන් සමඟ',
        point2: 'ඔබගේ ගනුදෙනු ආරක්ෂිතව හැසිරවීම සඳහා ගෙවීම් සකසන්නන් සමඟ',
        point3: 'නීතිය, අධිකරණ නියෝගය හෝ රජයේ රෙගුලාසි මගින් අවශ්‍ය වූ විට',
      },

      section4: {
        title: '4. දත්ත ආරක්ෂාව',
        content: 'අනවසර ප්‍රවේශය, වෙනස් කිරීම හෝ හෙළිදරව් කිරීමෙන් ඔබගේ පුද්ගලික තොරතුරු ආරක්ෂා කිරීම සඳහා අපි ශක්තිමත් ආරක්ෂක පියවර ක්‍රියාත්මක කරමු.',
        point1: 'දත්ත සම්ප්‍රේෂණය සහ ගබඩාව සඳහා කර්මාන්ත ප්‍රමිතියේ සංකේතනය',
        point2: 'විශ්වාසදායක සහ සහතික කළ ගෙවීම් ද්වාර හරහා ආරක්ෂිත ගෙවීම් සැකසීම',
        point3: 'අවදානම්වලින් ආරක්ෂා වීම සඳහා නිතිපතා ආරක්ෂක විගණන සහ යාවත්කාලීන',
        point4: 'දැනගැනීමට අවශ්‍ය පදනම මත පුද්ගලික තොරතුරු වෙත සීමිත ප්‍රවේශය',
      },

      section5: {
        title: '5. ඔබගේ අයිතිවාසිකම් සහ තේරීම්',
        content: 'ඔබගේ පුද්ගලික තොරතුරු සහ අපි එය භාවිතා කරන ආකාරය සම්බන්ධයෙන් ඔබට ඇතැම් අයිතිවාසිකම් ඇත.',
        point1: 'අපගේ සහාය කණ්ඩායම අමතා ඔබගේ පුද්ගලික තොරතුරු වෙත ප්‍රවේශ වීම සහ සමාලෝචනය කිරීම',
        point2: 'වැරදි හෝ අසම්පූර්ණ තොරතුරු නිවැරදි කිරීමට ඉල්ලීම',
        point3: 'නීතිමය සහ ගිවිසුම්ගත බැඳීම් වලට යටත්ව, ඔබගේ පුද්ගලික දත්ත මකා දැමීමට ඉල්ලීම',
      },

      section6: {
        title: '6. කුකීස් සහ ලුහුබැඳීම',
        content: 'ඔබගේ බ්‍රවුස් කිරීමේ අත්දැකීම වැඩිදියුණු කිරීමට සහ වෙබ් අඩවි භාවිතය විශ්ලේෂණය කිරීමට අපි කුකීස් සහ සමාන තාක්ෂණයන් භාවිතා කරමු.',
        point1: 'වෙබ් අඩවි ක්‍රියාකාරිත්වය සහ ආරක්ෂාව සඳහා අවශ්‍ය කුකීස්',
        point2: 'අමුත්තන් අපගේ වෙබ් අඩවිය භාවිතා කරන ආකාරය තේරුම් ගැනීමට විශ්ලේෂණ කුකීස්',
        point3: 'ඔබගේ බ්‍රව්සර් මනාපයන් හරහා කුකී සැකසීම් පාලනය කළ හැක',
      },

      contact: 'රහස්‍යතාව පිළිබඳව අප හා සම්බන්ධ වන්න',
      contactText: 'අපගේ රහස්‍යතා ප්‍රතිපත්තිය හෝ අපි ඔබගේ පුද්ගලික තොරතුරු හසුරුවන ආකාරය පිළිබඳව ඔබට කිසියම් ප්‍රශ්නයක් හෝ කනස්සල්ලක් ඇත්නම්, කරුණාකර අප හා සම්බන්ධ වන්න:',
      email: 'විද්‍යුත් තැපෑල',
      phone: 'දුරකථන',
    },

    refund: {
      title: 'ආපසු ගෙවීම් සහ නැවත සැලසුම්කරණ ප්‍රතිපත්තිය',
      mainTitle: 'ආපසු ගෙවීම් සහ නැවත සැලසුම්කරණ ප්‍රතිපත්තිය',
      mainDescription: 'වෙන්කිරීමක් කිරීමට පෙර කරුණාකර අපගේ ආපසු ගෙවීම් සහ නැවත සැලසුම්කරණ ප්‍රතිපත්තිය ප්‍රවේශමෙන් කියවන්න. මුදල් ආපසු ගෙවීම වෙනුවට අපි නම්‍යශීලී නැවත සැලසුම්කරණ විකල්ප ලබා දෙන්නෙමු.',
      lastUpdated: 'අවසන් යාවත්කාලීනය',

      noCashRefunds: 'මුදල් ආපසු නොගෙවයි',
      noCashRefundsText: 'කරුණාකර සලකන්න, අපි කිසිදු වෙන්කිරීමක් සඳහා මුදල් ආපසු ගෙවීමක් සපයන්නේ නැත. කෙසේ වෙතත්, නිශ්චිත කාල සීමාව තුළ ඔබට ඔබගේ වෙන්කිරීම වෙනත් දිනයකට නැවත සැලසුම් කළ හැකි අතර විවිධ ආසන තෝරා ගත හැක.',

      reschedulePolicy: 'නැවත සැලසුම්කරණ ප්‍රතිපත්තිය',
      reschedulePolicyDesc: 'සැලසුම් වෙනස් විය හැකි බව අපි තේරුම් ගනිමු. ඒ නිසා අපි ඔබගේ වෙන්කිරීම් සඳහා නම්‍යශීලී නැවත සැලසුම්කරණ විකල්පයක් ලබා දෙන්නෙමු.',

      whatYouCanDo: 'ඔබට කළ හැක්කේ කුමක්ද',
      canDo1: 'ඔබ වෙන්කිරීම සිදු කළ දිනයේ සිට දින 7ක් ඇතුළත ඔබගේ වත්මන් වෙන්කිරීම අවලංගු කරන්න',
      canDo2: 'ඕනෑම ලබා ගත හැකි දිනයකට සහ මාර්ගයකට නැවත සැලසුම් කරන්න',
      canDo3: 'ලබා ගත හැකි භාවය මත විවිධ ආසන අංක තෝරන්න',

      importantTimeline: 'වැදගත් කාල රාමුව',
      within7Days: 'දින 7ක් ඇතුළත',
      within7DaysDesc: 'ඔබ වෙන්කිරීම් දිනයෙන් (ගමන් දිනය නොව) දින 7ක් ඇතුළත එය සිදු කළහොත් ඔබට ඔබගේ වෙන්කිරීම අවලංගු කර නැවත සැලසුම් කළ හැක. දින 7 කාලය ආරම්භ වන්නේ ඔබ වෙන්කිරීම සම්පූර්ණ කළ මොහොතේ සිටය.',
      after7Days: 'දින 7කට පසු',
      after7DaysDesc: 'වෙන්කිරීම් දිනයෙන් දින 7කට පසු කරන ලද නැවත සැලසුම්කරණ ඉල්ලීම් භාර ගනු නොලැබේ. ඔබගේ වෙන්කිරීම ආපසු ගෙවිය නොහැකි සහ මාරු කළ නොහැකි වේ.',

      howToRequest: 'නැවත සැලසුම්කරණය ඉල්ලා සිටින ආකාරය',
      howToRequestDesc: 'ඔබගේ වෙන්කිරීම නැවත සැලසුම් කිරීමට මෙම සරල පියවර අනුගමනය කරන්න:',

      step1Title: 'අප හා සම්බන්ධ වන්න',
      step1Desc: 'ඔබගේ වෙන්කිරීමේ ID සහ නැවත සැලසුම්කරණය සඳහා හේතුව සමඟ අපගේ පාරිභෝගික සහාය අමතන්න හෝ විද්‍යුත් තැපෑලක් යවන්න.',

      step2Title: 'ඔබගේ වෙන්කිරීම සත්‍යාපනය කරන්න',
      step2Desc: 'ඔබගේ අනන්‍යතාවය සත්‍යාපනය කිරීම සඳහා ඔබගේ වෙන්කිරීමේ ID, දුරකථන අංකය සහ අනෙකුත් විස්තර සපයන්න.',

      step3Title: 'නව දිනය සහ ආසන තෝරන්න',
      step3Desc: 'ලබා ගත හැකි භාවය මත ඔබට කැමති නව ගමන් දිනය, මාර්ගය සහ ආසන අංක තෝරන්න.',

      step4Title: 'තහවුරු කිරීම',
      step4Desc: 'තහවුරු වූ පසු, ඔබට යාවත්කාලීන විස්තර සහිත නව වෙන්කිරීමේ තහවුරුවක් ලැබෙනු ඇත.',

      importantNotes: 'වැදගත් සටහන්',
      note1: 'දින 7 කාලය ගණනය කරනු ලබන්නේ ඔබගේ වෙන්කිරීමේ දිනයෙන් මිස ඔබගේ ගමන් දිනයෙන් නොවේ.',
      note2: 'නැවත සැලසුම්කරණය ඔබ තෝරාගත් නව දිනයේ ආසන ලබා ගත හැකි භාවයට යටත් වේ.',
      note3: 'ඔබට නැවත සැලසුම් කළ හැක්කේ එක් වරක් පමණි. බහු නැවත සැලසුම්කරණ ඉල්ලීම් වලට අවසර නැත.',
      note4: 'මුල් වෙන්කිරීම අතරතුර ගෙවූ සේවා ගාස්තුව ආපසු ගෙවිය නොහැකි අතර නැවත සැලසුම් කළ වෙන්කිරීම සඳහා යොදා ගනු ලැබේ.',

      needHelp: 'නැවත සැලසුම්කරණය සඳහා උදව් අවශ්‍යද?',
      needHelpText: 'ඔබගේ වෙන්කිරීම නැවත සැලසුම් කිරීමට ඔබට සහාය වීමට අපගේ පාරිභෝගික සහාය කණ්ඩායම මෙහි සිටී. අප හා සම්බන්ධ වන්න:',
      email: 'විද්‍යුත් තැපෑල',
      phone: 'දුරකථන',
      hours: 'සහාය පැය',
      hoursText: 'සඳුදා - ඉරිදා, පෙ.ව. 8:00 - ප.ව. 8:00',
    },
  },
};